# Generated by Django 2.2.6 on 2019-10-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('sex', models.PositiveIntegerField(choices=[(0, 'Female'), (1, 'Male')])),
                ('marital_status', models.PositiveIntegerField(choices=[(0, 'Single'), (1, 'Married'), (2, 'Divorced')])),
                ('national_id_card_no', models.CharField(blank=True, max_length=50)),
                ('drivers_licence_no', models.CharField(blank=True, max_length=50)),
                ('lashma_no', models.CharField(blank=True, max_length=50)),
                ('lashma_quality_life_no', models.CharField(blank=True, max_length=50)),
                ('lagos_resident_no', models.CharField(blank=True, max_length=50)),
                ('phone_no', models.CharField(blank=True, max_length=50)),
                ('whatsapp_no', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
