# Generated by Django 2.2.6 on 2019-10-07 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_no', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HMO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ranger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='home_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='informal_sector_group',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='occupation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='office_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='package_option',
            field=models.PositiveIntegerField(choices=[(0, 'LASHMA'), (1, 'LASHMA QUALITY LIFE')], null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_instrument',
            field=models.PositiveIntegerField(choices=[(0, 'Transfer'), (1, 'E-Wallet'), (2, 'Cheque'), (3, 'Bank Deposit')], null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_option',
            field=models.PositiveIntegerField(choices=[(0, 'Weekly'), (1, 'Monthly'), (2, 'Quarterly'), (3, 'Annually')], null=True),
        ),
        migrations.CreateModel(
            name='Dependant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('designation', models.PositiveIntegerField(choices=[(0, 'Spouse'), (1, 'Daughter'), (2, 'Son'), (3, 'Others')])),
                ('pcp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.CareProvider')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='dependants',
            field=models.ManyToManyField(blank=True, to='client.Dependant'),
        ),
        migrations.AddField(
            model_name='client',
            name='hmo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.HMO'),
        ),
        migrations.AddField(
            model_name='client',
            name='pcp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.CareProvider'),
        ),
        migrations.AddField(
            model_name='client',
            name='ranger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.Ranger'),
        ),
    ]
