# Generated by Django 2.2.6 on 2019-10-07 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20191007_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='dependants',
        ),
        migrations.AddField(
            model_name='dependant',
            name='primary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.Client'),
        ),
    ]
