# Generated by Django 2.2.6 on 2019-10-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20191023_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10, null=True),
        ),
    ]
