# Generated by Django 2.2.6 on 2019-10-07 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20191007_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='careprovider',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='careprovider',
            name='phone1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='careprovider',
            name='phone2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.LGA')),
            ],
        ),
        migrations.AddField(
            model_name='careprovider',
            name='lga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.LGA'),
        ),
        migrations.AddField(
            model_name='ranger',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.Location'),
        ),
    ]
