# Generated by Django 2.2.6 on 2019-10-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20191007_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careprovider',
            name='code_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
