# Generated by Django 2.2.6 on 2019-10-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_clientassociation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientassociation',
            options={'verbose_name': 'Associations'},
        ),
    ]
