# Generated by Django 2.2.6 on 2019-10-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='payment_instrument',
            field=models.CharField(choices=[('T', 'Transfer'), ('D', 'Debit Card'), ('E', 'E-Wallet'), ('C', 'Cheque'), ('B', 'Bank Deposit')], max_length=20, null=True),
        ),
    ]
