# Generated by Django 2.2.6 on 2019-11-11 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20191029_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientassociation',
            options={'verbose_name': 'Association'},
        ),
    ]
