# Generated by Django 2.2.6 on 2019-10-08 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20191007_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranger',
            name='location',
        ),
        migrations.AddField(
            model_name='ranger',
            name='lga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.LGA'),
        ),
    ]
