# Generated by Django 2.2.6 on 2019-10-08 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20191008_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='hmo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.HMO'),
        ),
        migrations.AlterField(
            model_name='client',
            name='informal_sector_group',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='pcp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.CareProvider'),
        ),
    ]
