# Generated by Django 2.2.6 on 2019-10-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_auto_20191009_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='package_option',
            field=models.CharField(choices=[('L', 'LASHMA'), ('Q', 'LASHMA QUALITY LIFE')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='payment_instrument',
            field=models.CharField(choices=[('T', 'Transfer'), ('E', 'E-Wallet'), ('C', 'Cheque'), ('B', 'Bank Deposit')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='payment_option',
            field=models.CharField(choices=[('W', 'Weekly'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('A', 'Annually')], max_length=50, null=True),
        ),
    ]
