# Generated by Django 2.2.6 on 2019-10-09 03:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20191009_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
