# Generated by Django 2.2.6 on 2019-11-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_auto_20191120_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='verification_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
