# Generated by Django 2.2.6 on 2019-11-30 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_client_verification_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
