# Generated by Django 2.2.6 on 2019-10-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20191018_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='informal_sector_group',
        ),
        migrations.AddField(
            model_name='client',
            name='associations',
            field=models.ManyToManyField(to='client.Association'),
        ),
    ]
