# Generated by Django 2.2.6 on 2019-12-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_client_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='verification_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
