# Generated by Django 2.2.6 on 2019-12-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_client_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='payment_option',
            field=models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('A', 'Annually')], max_length=50, null=True),
        ),
    ]
