# Generated by Django 2.2.6 on 2019-12-18 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_auto_20191212_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependant',
            name='pcp',
        ),
    ]
