# Generated by Django 2.2.6 on 2020-01-27 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_remove_dependant_pcp'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyClient',
            fields=[
            ],
            options={
                'verbose_name': 'Client (for Payment)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('client.client',),
        ),
    ]
