# Generated by Django 2.2.6 on 2020-02-03 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_auto_20200128_0520'),
        ('client', '0022_dependant_photo'),
    ]

    operations = [
    ]
