# Generated by Django 2.2.8 on 2020-02-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0024_client_uses_default_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='verification_code_verified',
            field=models.BooleanField(default=False),
        ),
    ]
