# Generated by Django 2.2.8 on 2020-02-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0025_client_verification_code_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='verification_code_verified',
            field=models.BooleanField(default=True),
        ),
    ]
