# Generated by Django 2.2.8 on 2020-02-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0027_remove_client_verification_code_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempClientUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=30)),
                ('relationship', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('premium', models.CharField(max_length=50)),
                ('state_id', models.CharField(max_length=150)),
                ('national_id', models.CharField(max_length=150)),
                ('passport', models.CharField(max_length=150)),
                ('staff_id', models.CharField(max_length=150)),
                ('voter_id', models.CharField(max_length=150)),
                ('secondary_phone_no', models.CharField(max_length=150)),
                ('lga', models.CharField(max_length=150)),
                ('provider', models.CharField(max_length=150)),
            ],
        ),
    ]
