# Generated by Django 2.2.8 on 2020-02-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0028_tempclientupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempclientupload',
            name='dob',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tempclientupload',
            name='lga',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tempclientupload',
            name='middle_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tempclientupload',
            name='national_id',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tempclientupload',
            name='passport',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tempclientupload',
            name='premium',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tempclientupload',
            name='provider',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tempclientupload',
            name='relationship',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tempclientupload',
            name='salutation',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tempclientupload',
            name='secondary_phone_no',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tempclientupload',
            name='staff_id',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tempclientupload',
            name='state_id',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tempclientupload',
            name='voter_id',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
