# Generated by Django 2.2.8 on 2020-02-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0029_auto_20200219_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempclientupload',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tempclientupload',
            name='gender',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tempclientupload',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tempclientupload',
            name='phone_no',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
