# Generated by Django 2.2.8 on 2020-02-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0031_auto_20200224_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='drivers_licence_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='lagos_resident_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='lashma_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='lashma_quality_life_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='national_id_card_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='whatsapp_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
