# Generated by Django 2.2.8 on 2020-02-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0032_auto_20200224_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempclientupload',
            name='lshs_code',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tempclientupload',
            name='package',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tempclientupload',
            name='period',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tempclientupload',
            name='ql_code',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
