# Generated by Django 2.2.8 on 2020-02-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0036_auto_20200225_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempRequestStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=300)),
                ('post_data', models.TextField(blank=True, null=True)),
                ('json_data', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
