# Generated by Django 2.2.8 on 2020-02-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0037_temprequeststore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='home_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='occupation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='office_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
