# Generated by Django 2.2.8 on 2020-02-29 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0038_auto_20200229_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependant',
            name='primary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Client'),
        ),
    ]
