# Generated by Django 2.2.8 on 2020-03-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0039_auto_20200229_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
