# Generated by Django 2.2.8 on 2020-03-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0041_adhocclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='lashma_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dependant',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dependant',
            name='salutation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
