# Generated by Django 2.2.8 on 2020-03-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0042_auto_20200326_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='salutation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
