# Generated by Django 2.2.8 on 2020-05-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0044_historicaladhocclient_historicalassociation_historicalclient_historicalclientassociation_historicald'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=200)),
                ('middle_name', models.CharField(blank=True, default='', max_length=200)),
                ('last_name', models.CharField(blank=True, default='', max_length=200)),
                ('salutation', models.CharField(blank=True, default='', max_length=200)),
                ('gender', models.CharField(blank=True, default='', max_length=200)),
                ('phone_number', models.CharField(blank=True, default='', max_length=200)),
                ('date_of_birth', models.CharField(blank=True, default='', max_length=200)),
                ('age_today', models.CharField(blank=True, default='', max_length=200)),
                ('marital_status', models.CharField(blank=True, default='', max_length=200)),
                ('sub_region', models.CharField(blank=True, default='', max_length=200)),
                ('participant_status', models.CharField(blank=True, default='', max_length=200)),
                ('date_created', models.CharField(blank=True, default='', max_length=200)),
                ('policy_status', models.CharField(blank=True, default='', max_length=200)),
                ('policy_activation_date', models.CharField(blank=True, default='', max_length=200)),
                ('policy_expiry_date', models.CharField(blank=True, default='', max_length=200)),
                ('relationship', models.CharField(blank=True, default='', max_length=200)),
                ('membership_number', models.CharField(blank=True, default='', max_length=200)),
                ('policy_number', models.CharField(blank=True, default='', max_length=200)),
                ('insurance_package', models.CharField(blank=True, default='', max_length=200)),
                ('premium_amount', models.CharField(blank=True, default='', max_length=200)),
                ('staff_id', models.CharField(blank=True, default='', max_length=200)),
                ('driving_licence', models.CharField(blank=True, default='', max_length=200)),
                ('voter_id', models.CharField(blank=True, default='', max_length=200)),
                ('military_id', models.CharField(blank=True, default='', max_length=200)),
                ('secondary_phone_number', models.CharField(blank=True, default='', max_length=200)),
                ('employer', models.CharField(blank=True, default='', max_length=200)),
                ('agent', models.CharField(blank=True, default='', max_length=200)),
                ('agent_phone_number', models.CharField(blank=True, default='', max_length=200)),
                ('registration_agency', models.CharField(blank=True, default='', max_length=200)),
                ('administration_agency', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
