# Generated by Django 2.2.8 on 2020-05-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0045_uploadedclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedclient',
            name='national_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='uploadedclient',
            name='participant_policy_status',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='uploadedclient',
            name='passport',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='uploadedclient',
            name='provider_code',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='uploadedclient',
            name='provider_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='uploadedclient',
            name='provider_ownership',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='uploadedclient',
            name='state_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
