# Generated by Django 2.2.8 on 2020-05-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0046_auto_20200519_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='membership_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='membership_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
