# Generated by Django 2.2.8 on 2021-02-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0047_auto_20200521_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependant',
            name='salutation',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldependant',
            name='salutation',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
