# Generated by Django 2.2.6 on 2019-11-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=1, unique=True)),
                ('client_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('spouse_dependant_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('minor_dependant_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_dependant_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
