# Generated by Django 2.2.6 on 2019-12-11 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='client_rate',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='minor_dependant_rate',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='other_dependant_rate',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='spouse_dependant_rate',
        ),
        migrations.AddField(
            model_name='plan',
            name='has_extra',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PlanRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_cycle', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('A', 'Annually')], max_length=2)),
                ('rate', models.PositiveIntegerField()),
                ('extra_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Plan')),
            ],
        ),
    ]
