# Generated by Django 2.2.6 on 2019-12-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_plan_family_inclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='size',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
