# Generated by Django 2.2.6 on 2019-12-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20191215_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cust_reference',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
