# Generated by Django 2.2.6 on 2020-01-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_cust_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='narration',
            field=models.TextField(blank=True, null=True),
        ),
    ]
