# Generated by Django 2.2.8 on 2020-06-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(blank=True, choices=[('S', 'Successful'), ('F', 'Failed')], default='', max_length=200),
        ),
    ]
