# Generated by Django 2.2.8 on 2020-06-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20200606_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smslog',
            old_name='sender',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='smslog',
            name='sms_sender',
            field=models.CharField(default='FutureCare', max_length=15),
        ),
    ]
