# Generated by Django 2.2.6 on 2019-10-08 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_no', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(null=True)),
                ('phone1', models.CharField(blank=True, max_length=100, null=True)),
                ('phone2', models.CharField(blank=True, max_length=100, null=True)),
                ('lga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.LGA')),
            ],
        ),
    ]
