# Generated by Django 2.2.8 on 2020-06-19 09:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_historicalcareprovider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careprovider',
            options={'permissions': (('is_provider', 'Care Provider'),)},
        ),
        migrations.AddField(
            model_name='careprovider',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 19, 9, 42, 13, 507050, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='careprovider',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='careprovider',
            name='uses_default_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcareprovider',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 19, 9, 42, 24, 382111, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcareprovider',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historicalcareprovider',
            name='uses_default_password',
            field=models.BooleanField(default=False),
        ),
    ]
