# Generated by Django 2.2.6 on 2019-11-30 07:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0013_delete_subscription'),
        ('ranger', '0007_walletfunding_reference'),
        ('payment', '0002_auto_20191120_0846'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Pending'), (1, 'Failed'), (2, 'Successful')], default=0)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.Payment')),
                ('ranger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ranger.Ranger')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateField(null=True)),
                ('expiry_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
                ('dependants', models.ManyToManyField(to='client.Dependant')),
                ('next_subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.Subscription')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Plan')),
            ],
        ),
    ]
