# Generated by Django 2.2.6 on 2019-12-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='payment_type',
            field=models.PositiveIntegerField(choices=[(0, 'Bank Transfer'), (1, 'Bank Deposit'), (2, 'Card')], default=0),
        ),
    ]
