# Generated by Django 2.2.6 on 2019-12-18 21:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ranger', '0008_auto_20191217_2042'),
        ('subscription', '0002_subscriptionpayment_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subscription_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('when', models.DateTimeField(default=django.utils.timezone.now)),
                ('ranger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranger.Ranger')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.Subscription')),
            ],
        ),
    ]
