# Generated by Django 2.2.6 on 2020-01-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='payment_type',
            field=models.PositiveIntegerField(choices=[(0, 'Bank Transfer'), (1, 'Bank Deposit'), (2, 'Card'), (3, 'Agent')], default=0),
        ),
    ]
