# Generated by Django 2.2.6 on 2019-10-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranger',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
