# Generated by Django 2.2.6 on 2019-11-11 19:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('ranger', '0002_ranger_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletFunding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Pending'), (1, 'Failed'), (2, 'Successful')], default=0)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.Payment')),
                ('ranger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranger.Ranger')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
