# Generated by Django 2.2.6 on 2019-11-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranger', '0004_auto_20191120_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletfunding',
            name='payment_type',
            field=models.PositiveIntegerField(choices=[(0, 'Bank Transfer'), (1, 'Bank Deposit')], default=0),
        ),
    ]
