# Generated by Django 2.2.6 on 2019-11-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranger', '0005_walletfunding_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletfunding',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
