# Generated by Django 2.2.6 on 2019-11-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranger', '0006_walletfunding_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletfunding',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
