# Generated by Django 2.2.6 on 2019-12-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranger', '0007_walletfunding_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletfunding',
            name='payment_type',
            field=models.PositiveIntegerField(choices=[(0, 'Bank Transfer'), (1, 'Bank Deposit'), (2, 'Paystack')], default=0),
        ),
    ]
