# Generated by Django 2.2.8 on 2020-03-23 17:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ranger', '0008_auto_20191217_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranger',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 3, 23, 17, 42, 27, 287233, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
